import os
import io

import numpy as np
import tensorflow as tf
import streamlit as st

from PIL import Image
from fpdf import FPDF

from modality_model_builder import (
    build_modality_classifier
)

from model_builder import (
    build_model
)


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Pneumonia AI",
    page_icon="🫁",
    layout="wide"
)


# ============================================================
# MODEL PATHS
# ============================================================

MODALITY_MODEL_PATH = (
    "best_modality_classifier.weights.h5"
)

PNEUMONIA_MODEL_PATH = (
    "best_xception_pneumonia_model.keras"
)


# ============================================================
# IMAGE SIZE
# ============================================================

MODALITY_IMAGE_SIZE = (
    128,
    128
)

PNEUMONIA_IMAGE_SIZE = (
    224,
    224
)


# ============================================================
# MODALITY CLASS MAPPING
# ============================================================
#
# This MUST match:
#
# {
#     'CHEST_XRAY': 0,
#     'CT': 1,
#     'MRI': 2,
#     'OTHER': 3
# }
#
# generated by flow_from_directory().
# ============================================================

MODALITY_CLASS_NAMES = [
    "CHEST_XRAY",
    "CT",
    "MRI",
    "OTHER"
]


# ============================================================
# CHEST X-RAY ACCEPTANCE THRESHOLD
# ============================================================
#
# This is intentionally lower than 0.50 to avoid rejecting
# valid X-ray images because of small differences in image
# quality, cropping, contrast, or preprocessing.
#
# IMPORTANT:
# The image must STILL have CHEST_XRAY as the highest
# probability.
# ============================================================

CHEST_XRAY_THRESHOLD = 0.35


# ============================================================
# SESSION STATE
# ============================================================

if "history" not in st.session_state:

    st.session_state.history = []


# ============================================================
# LOAD MODALITY MODEL
# ============================================================

@st.cache_resource
def load_modality_model():

    if not os.path.isfile(
        MODALITY_MODEL_PATH
    ):

        raise FileNotFoundError(
            "Modality model weights not found:\n"
            f"{MODALITY_MODEL_PATH}"
        )

    model = build_modality_classifier(

        input_shape=(
            128,
            128,
            3
        ),

        num_classes=4
    )

    model.load_weights(
        MODALITY_MODEL_PATH
    )

    return model


# ============================================================
# LOAD PNEUMONIA MODEL
# ============================================================

@st.cache_resource
def load_pneumonia_model():

    if not os.path.isfile(
        PNEUMONIA_MODEL_PATH
    ):

        raise FileNotFoundError(
            "Pneumonia model not found:\n"
            f"{PNEUMONIA_MODEL_PATH}"
        )

    model = build_model(
        input_shape=(
            224,
            224,
            3
        )
    )

    # --------------------------------------------------------
    # Load complete .keras model
    # --------------------------------------------------------

    try:

        loaded_model = tf.keras.models.load_model(
            PNEUMONIA_MODEL_PATH,
            compile=False
        )

        return loaded_model

    except Exception:

        # ----------------------------------------------------
        # Fallback: build architecture and load weights
        # ----------------------------------------------------

        model.load_weights(
            PNEUMONIA_MODEL_PATH
        )

        return model


# ============================================================
# LOAD MODELS
# ============================================================

try:

    modality_model = load_modality_model()

    pneumonia_model = load_pneumonia_model()

except Exception as e:

    st.error(
        "Model loading failed."
    )

    st.exception(e)

    st.stop()


# ============================================================
# HEADER
# ============================================================

st.title(
    "🫁 Pneumonia Detection System"
)

st.markdown(
    """
Upload an image to the system.

**Step 1:** Verify the medical image modality.

**Step 2:** Continue only if the image is a chest X-ray.

**Step 3:** Detect whether the chest X-ray is Normal or Pneumonia.
"""
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header(
        "About the System"
    )

    st.write(
        "This application uses two deep-learning models:"
    )

    st.write(
        "1. Medical image modality verification"
    )

    st.write(
        "2. Pneumonia detection"
    )

    st.divider()

    st.header(
        "Recent Scans"
    )

    if len(
        st.session_state.history
    ) == 0:

        st.write(
            "No scans yet."
        )

    else:

        for item in reversed(
            st.session_state.history[-10:]
        ):

            st.text(
                item
            )


# ============================================================
# FILE UPLOADER
# ============================================================

uploaded_file = st.file_uploader(

    "Upload an image",

    type=[
        "jpg",
        "jpeg",
        "png",
        "bmp",
        "webp"
    ],

    help=(
        "Upload a medical image. "
        "Only chest X-ray images will proceed "
        "to pneumonia detection."
    )
)


# ============================================================
# IMAGE PROCESSING
# ============================================================

if uploaded_file is not None:

    try:

        # ----------------------------------------------------
        # READ IMAGE
        # ----------------------------------------------------

        file_bytes = (
            uploaded_file.getvalue()
        )

        image = Image.open(
            io.BytesIO(file_bytes)
        ).convert("RGB")


        # ----------------------------------------------------
        # DISPLAY IMAGE
        # ----------------------------------------------------

        st.image(
            image,
            caption="Uploaded Image",
            use_container_width=True
        )


        # ----------------------------------------------------
        # ANALYZE BUTTON
        # ----------------------------------------------------

        if st.button(
            "Analyze Image",
            type="primary"
        ):

            # =================================================
            # BASIC VALIDATION
            # =================================================

            if image is None:

                st.error(
                    "Could not read the uploaded image."
                )

                st.stop()


            # =================================================
            # STEP 1 — IMAGE VERIFICATION
            # =================================================

            st.subheader(
                "Step 1 — Image Verification"
            )

            st.subheader(
                "Medical Image Modality Verification"
            )


            # =================================================
            # PREPARE MODALITY INPUT
            # =================================================
            #
            # IMPORTANT:
            #
            # The MobileNetV2 modality model was trained using
            # MobileNetV2 preprocessing.
            #
            # DO NOT use /255.0 here.
            #
            # =================================================

            modality_image = image.resize(
                MODALITY_IMAGE_SIZE,
                Image.Resampling.LANCZOS
            )

            modality_array = np.asarray(
                modality_image,
                dtype=np.float32
            )


            # -------------------------------------------------
            # MobileNetV2 preprocessing
            # Converts [0,255] -> [-1,1]
            # -------------------------------------------------

            modality_array = (
                tf.keras.applications
                .mobilenet_v2
                .preprocess_input(
                    modality_array
                )
            )


            modality_input = np.expand_dims(
                modality_array,
                axis=0
            )


            # =================================================
            # MODALITY PREDICTION
            # =================================================

            with st.spinner(
                "Verifying image modality..."
            ):

                modality_prediction = (
                    modality_model.predict(
                        modality_input,
                        verbose=0
                    )
                )


            modality_prediction = np.asarray(
                modality_prediction
            )


            # =================================================
            # VALIDATE OUTPUT
            # =================================================

            if modality_prediction.ndim != 2:

                st.error(
                    "Invalid modality model output."
                )

                st.stop()


            if modality_prediction.shape[1] != 4:

                st.error(
                    "Modality model must produce "
                    "4 class probabilities."
                )

                st.write(
                    "Output shape:",
                    modality_prediction.shape
                )

                st.stop()


            # =================================================
            # GET PROBABILITIES
            # =================================================

            modality_probabilities = (
                modality_prediction[0]
                .astype(np.float64)
            )


            # =================================================
            # SAFETY CHECK
            # =================================================

            probability_sum = np.sum(
                modality_probabilities
            )


            if (

                np.any(
                    modality_probabilities < 0
                )

                or

                np.any(
                    modality_probabilities > 1
                )

                or

                not np.isclose(
                    probability_sum,
                    1.0,
                    atol=1e-3
                )

            ):

                modality_probabilities = (
                    tf.nn.softmax(
                        modality_probabilities
                    ).numpy()
                )


            # =================================================
            # PREDICTED MODALITY
            # =================================================

            predicted_index = int(
                np.argmax(
                    modality_probabilities
                )
            )


            predicted_modality = (
                MODALITY_CLASS_NAMES[
                    predicted_index
                ]
            )


            predicted_confidence = float(
                modality_probabilities[
                    predicted_index
                ]
            )


            chest_xray_probability = float(
                modality_probabilities[0]
            )


            ct_probability = float(
                modality_probabilities[1]
            )


            mri_probability = float(
                modality_probabilities[2]
            )


            other_probability = float(
                modality_probabilities[3]
            )


            # =================================================
            # MODALITY RESULTS
            # =================================================

            col1, col2, col3, col4 = st.columns(4)


            with col1:

                st.metric(
                    "Chest X-ray",
                    f"{chest_xray_probability * 100:.2f}%"
                )


            with col2:

                st.metric(
                    "CT",
                    f"{ct_probability * 100:.2f}%"
                )


            with col3:

                st.metric(
                    "MRI",
                    f"{mri_probability * 100:.2f}%"
                )


            with col4:

                st.metric(
                    "Other",
                    f"{other_probability * 100:.2f}%"
                )


            # =================================================
            # DECISION
            # =================================================
            #
            # TWO conditions are required:
            #
            # 1. CHEST_XRAY must be the highest class.
            #
            # 2. CHEST_XRAY probability must be >= threshold.
            #
            # =================================================

            is_chest_xray = (

                predicted_index == 0

                and

                chest_xray_probability
                >= CHEST_XRAY_THRESHOLD
            )


            # =================================================
            # NON-X-RAY / NON-CHEST-XRAY
            # =================================================

            if not is_chest_xray:

                if predicted_modality == "CT":

                    st.error(
                        "❌ CT scan detected."
                    )

                    st.warning(
                        "This system accepts only "
                        "chest X-ray images."
                    )


                elif predicted_modality == "MRI":

                    st.error(
                        "❌ MRI image detected."
                    )

                    st.warning(
                        "This system accepts only "
                        "chest X-ray images."
                    )


                elif predicted_modality == "OTHER":

                    st.error(
                        "❌ Unsupported image detected."
                    )

                    st.warning(
                        "Please upload a chest X-ray image."
                    )


                else:

                    st.error(
                        "❌ Chest X-ray confidence is too low."
                    )

                    st.warning(
                        "Please upload a clear chest X-ray image."
                    )


                st.write(
                    f"Detected modality: "
                    f"**{predicted_modality}**"
                )


                st.write(
                    f"Modality confidence: "
                    f"{predicted_confidence * 100:.2f}%"
                )


                # ------------------------------------------------
                # HISTORY
                # ------------------------------------------------

                history_entry = (
                    f"Rejected - "
                    f"{predicted_modality} - "
                    f"{uploaded_file.name}"
                )


                if (
                    history_entry
                    not in st.session_state.history
                ):

                    st.session_state.history.append(
                        history_entry
                    )


                st.stop()


            # =================================================
            # CHEST X-RAY CONFIRMED
            # =================================================

            st.success(
                "✅ Chest X-ray image detected."
            )


            st.write(
                f"Chest X-ray confidence: "
                f"{chest_xray_probability * 100:.2f}%"
            )


            # =================================================
            # STEP 2 — PNEUMONIA DETECTION
            # =================================================

            st.subheader(
                "Step 2 — Pneumonia Detection"
            )


            # =================================================
            # PREPARE PNEUMONIA IMAGE
            # =================================================

            pneumonia_image = image.resize(
                PNEUMONIA_IMAGE_SIZE,
                Image.Resampling.LANCZOS
            )


            pneumonia_array = np.asarray(
                pneumonia_image,
                dtype=np.float32
            )


            # -------------------------------------------------
            # IMPORTANT:
            #
            # Your pneumonia model was previously using
            # /255.0 preprocessing.
            #
            # Keep this separate from MobileNetV2
            # preprocessing.
            # -------------------------------------------------

            pneumonia_array = (
                pneumonia_array / 255.0
            )


            pneumonia_input = np.expand_dims(
                pneumonia_array,
                axis=0
            )


            # =================================================
            # RUN PNEUMONIA MODEL
            # =================================================

            with st.spinner(
                "Analyzing chest X-ray..."
            ):

                prediction = (
                    pneumonia_model.predict(
                        pneumonia_input,
                        verbose=0
                    )
                )


            prediction = np.asarray(
                prediction
            )


            # =================================================
            # REMOVE BATCH DIMENSION
            # =================================================

            prediction_values = np.squeeze(
                prediction
            )


            # =================================================
            # PNEUMONIA MODEL OUTPUT HANDLING
            # =================================================
            #
            # Supports:
            #
            # A) 2-class softmax:
            #
            # [Normal, Pneumonia]
            #
            # B) Single sigmoid:
            #
            # [Pneumonia probability]
            #
            # =================================================


            if prediction_values.ndim == 0:

                pneumonia_probability = float(
                    prediction_values
                )


            elif prediction_values.size == 1:

                pneumonia_probability = float(
                    prediction_values
                )


            elif prediction_values.size == 2:

                probabilities = (
                    prediction_values
                ).astype(
                    np.float64
                )


                # ---------------------------------------------
                # Check whether output is already probability
                # ---------------------------------------------

                if (

                    np.all(
                        probabilities >= 0
                    )

                    and

                    np.all(
                        probabilities <= 1
                    )

                    and

                    np.isclose(
                        np.sum(probabilities),
                        1.0,
                        atol=1e-3
                    )

                ):

                    pneumonia_probabilities = (
                        probabilities
                    )

                else:

                    pneumonia_probabilities = (
                        tf.nn.softmax(
                            probabilities
                        ).numpy()
                    )


                # ---------------------------------------------
                # IMPORTANT CLASS MAPPING
                #
                # Your directory structure should normally
                # produce:
                #
                # NORMAL = 0
                # PNEUMONIA = 1
                #
                # Therefore:
                #
                # index 0 = Normal
                # index 1 = Pneumonia
                # ---------------------------------------------

                normal_probability = float(
                    pneumonia_probabilities[0]
                )

                pneumonia_probability = float(
                    pneumonia_probabilities[1]
                )


            else:

                st.error(
                    "Unsupported pneumonia model output."
                )

                st.stop()


            # =================================================
            # SAFETY CLAMP
            # =================================================

            pneumonia_probability = float(
                np.clip(
                    pneumonia_probability,
                    0.0,
                    1.0
                )
            )


            # =================================================
            # NORMAL PROBABILITY
            # =================================================

            if (
                "normal_probability"
                not in locals()
            ):

                normal_probability = (
                    1.0
                    -
                    pneumonia_probability
                )

            else:

                normal_probability = float(
                    np.clip(
                        normal_probability,
                        0.0,
                        1.0
                    )
                )


            # =================================================
            # DIAGNOSIS
            # =================================================

            if (
                pneumonia_probability
                >= 0.50
            ):

                diagnosis = (
                    "Pneumonia"
                )

                diagnosis_confidence = (
                    pneumonia_probability
                )

                st.error(
                    "Diagnosis: Pneumonia"
                )

            else:

                diagnosis = (
                    "Normal"
                )

                diagnosis_confidence = (
                    normal_probability
                )

                st.success(
                    "Diagnosis: Normal"
                )


            # =================================================
            # FINAL RESULT
            # =================================================

            st.subheader(
                "Final Result"
            )


            col1, col2, col3 = st.columns(3)


            with col1:

                st.metric(
                    "X-ray Confidence",
                    f"{chest_xray_probability * 100:.2f}%"
                )


            with col2:

                st.metric(
                    "Normal",
                    f"{normal_probability * 100:.2f}%"
                )


            with col3:

                st.metric(
                    "Pneumonia",
                    f"{pneumonia_probability * 100:.2f}%"
                )


            st.write(
                f"**Final Diagnosis:** "
                f"{diagnosis}"
            )


            st.write(
                f"**Diagnosis Confidence:** "
                f"{diagnosis_confidence * 100:.2f}%"
            )


            # =================================================
            # HISTORY
            # =================================================

            history_entry = (
                f"{diagnosis} - "
                f"{uploaded_file.name}"
            )


            if (
                history_entry
                not in st.session_state.history
            ):

                st.session_state.history.append(
                    history_entry
                )


            # =================================================
            # DIAGNOSTIC REPORT
            # =================================================

            st.divider()

            st.subheader(
                "Diagnostic Report"
            )


            st.write(
                f"**File:** "
                f"{uploaded_file.name}"
            )

            st.write(
                "**Image Modality:** Chest X-ray"
            )

            st.write(
                f"**X-ray Confidence:** "
                f"{chest_xray_probability * 100:.2f}%"
            )

            st.write(
                f"**Diagnosis:** "
                f"{diagnosis}"
            )

            st.write(
                f"**Diagnosis Confidence:** "
                f"{diagnosis_confidence * 100:.2f}%"
            )


            # =================================================
            # PDF REPORT
            # =================================================

            clean_filename = (
                uploaded_file.name
                .encode(
                    "ascii",
                    "ignore"
                )
                .decode(
                    "ascii"
                )
            )


            pdf = FPDF()

            pdf.add_page()


            pdf.set_font(
                "Arial",
                "B",
                18
            )


            pdf.cell(
                0,
                15,
                "Pneumonia AI Diagnostic Report",
                ln=True,
                align="C"
            )


            pdf.line(
                10,
                25,
                200,
                25
            )


            pdf.ln(10)


            # ------------------------------------------------
            # FILE NAME
            # ------------------------------------------------

            pdf.set_font(
                "Arial",
                "B",
                12
            )

            pdf.cell(
                45,
                10,
                "File Name:",
                ln=False
            )


            pdf.set_font(
                "Arial",
                "",
                12
            )

            pdf.cell(
                0,
                10,
                clean_filename,
                ln=True
            )


            # ------------------------------------------------
            # IMAGE MODALITY
            # ------------------------------------------------

            pdf.set_font(
                "Arial",
                "B",
                12
            )

            pdf.cell(
                45,
                10,
                "Image Modality:",
                ln=False
            )


            pdf.set_font(
                "Arial",
                "",
                12
            )

            pdf.cell(
                0,
                10,
                "Chest X-ray",
                ln=True
            )


            # ------------------------------------------------
            # X-RAY CONFIDENCE
            # ------------------------------------------------

            pdf.set_font(
                "Arial",
                "B",
                12
            )

            pdf.cell(
                45,
                10,
                "X-ray Confidence:",
                ln=False
            )


            pdf.set_font(
                "Arial",
                "",
                12
            )

            pdf.cell(
                0,
                10,
                f"{chest_xray_probability * 100:.2f}%",
                ln=True
            )


            # ------------------------------------------------
            # DIAGNOSIS
            # ------------------------------------------------

            pdf.set_font(
                "Arial",
                "B",
                12
            )

            pdf.cell(
                45,
                10,
                "Diagnosis:",
                ln=False
            )


            pdf.set_font(
                "Arial",
                "",
                12
            )

            pdf.cell(
                0,
                10,
                diagnosis,
                ln=True
            )


            # ------------------------------------------------
            # CONFIDENCE
            # ------------------------------------------------

            pdf.set_font(
                "Arial",
                "B",
                12
            )

            pdf.cell(
                45,
                10,
                "Confidence:",
                ln=False
            )


            pdf.set_font(
                "Arial",
                "",
                12
            )

            pdf.cell(
                0,
                10,
                f"{diagnosis_confidence * 100:.2f}%",
                ln=True
            )


            pdf.ln(15)


            # ------------------------------------------------
            # DISCLAIMER
            # ------------------------------------------------

            pdf.set_font(
                "Arial",
                "I",
                10
            )

            pdf.multi_cell(
                0,
                7,
                "Disclaimer: "
                "This AI-generated result is intended "
                "for research purposes only and does not "
                "replace professional medical diagnosis."
            )


            # =================================================
            # PDF OUTPUT
            # =================================================

            pdf_output = pdf.output()


            st.download_button(

                label=(
                    "Download Diagnostic Report"
                ),

                data=bytes(
                    pdf_output
                ),

                file_name=(
                    f"Report_"
                    f"{clean_filename}.pdf"
                ),

                mime="application/pdf"
            )


    except Exception as e:

        st.error(
            "An error occurred while "
            "processing the image."
        )

        st.exception(e)
