import os
import io

import numpy as np
import tensorflow as tf
import streamlit as st

from PIL import Image

from model_builder import build_model
from xray_model_builder import build_xray_classifier
from modality_model_builder import build_modality_classifier


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Pneumonia AI",
    page_icon="🫁",
    layout="wide"
)


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.abspath(__file__)
)


# ============================================================
# MODEL PATHS
# ============================================================

XRAY_MODEL_PATH = os.path.join(
    BASE_DIR,
    "best_xray_verifier.weights.h5"
)

MODALITY_MODEL_PATH = os.path.join(
    BASE_DIR,
    "best_modality_classifier.weights.h5"
)

PNEUMONIA_MODEL_PATH = os.path.join(
    BASE_DIR,
    "best_xception_pneumonia_model.keras"
)


# ============================================================
# IMAGE SIZES
# ============================================================

XRAY_IMAGE_SIZE = (128, 128)

MODALITY_IMAGE_SIZE = (224, 224)

PNEUMONIA_IMAGE_SIZE = (224, 224)


# ============================================================
# CLASS CONFIGURATION
# ============================================================

# ------------------------------------------------------------
# MODALITY MODEL
# ------------------------------------------------------------
#
# THIS MUST MATCH TRAINING class_indices EXACTLY.
#
# Current expected 3-class configuration:
#
# 0 = X-RAY
# 1 = CT
# 2 = MRI
#
# ------------------------------------------------------------

MODALITY_CLASS_MAP = {
    0: "X-RAY",
    1: "CT",
    2: "MRI"
}

NUM_MODALITY_CLASSES = 3


# ------------------------------------------------------------
# X-RAY VERIFIER
# ------------------------------------------------------------
#
# This must match the training class order.
#
# ------------------------------------------------------------

XRAY_CLASS_MAP = {
    0: "X-RAY",
    1: "NON-XRAY"
}

XRAY_CLASS_INDEX = 0
NON_XRAY_CLASS_INDEX = 1


# ------------------------------------------------------------
# PNEUMONIA
# ------------------------------------------------------------
#
# 0 = Normal
# 1 = Pneumonia
#
# ------------------------------------------------------------

PNEUMONIA_CLASS_MAP = {
    0: "Normal",
    1: "Pneumonia"
}


# ============================================================
# THRESHOLDS
# ============================================================

MODALITY_CONFIDENCE_THRESHOLD = 0.90

XRAY_CONFIDENCE_THRESHOLD = 0.50


# ============================================================
# GRAYSCALE VALIDATION
# ============================================================

COLOR_TOLERANCE = 5.0


# ============================================================
# SESSION STATE
# ============================================================

if "history" not in st.session_state:

    st.session_state.history = []


# ============================================================
# FILE VALIDATION
# ============================================================

def check_model_file(
    path,
    model_name
):

    if not os.path.isfile(path):

        raise FileNotFoundError(
            f"{model_name} was not found.\n\n"
            f"Expected location:\n{path}\n\n"
            f"Make sure the file is committed to "
            f"the same repository as streamlit_app.py."
        )

    if os.path.getsize(path) == 0:

        raise RuntimeError(
            f"{model_name} exists but is empty:\n{path}"
        )


# ============================================================
# LOAD MODALITY MODEL
# ============================================================

@st.cache_resource
def load_modality_model():

    check_model_file(
        MODALITY_MODEL_PATH,
        "Medical modality classifier weights"
    )

    try:

        # IMPORTANT:
        # This architecture MUST be identical
        # to the architecture used during training.

        model = build_modality_classifier(
            input_shape=(
                MODALITY_IMAGE_SIZE[0],
                MODALITY_IMAGE_SIZE[1],
                3
            ),
            num_classes=NUM_MODALITY_CLASSES
        )

        model.load_weights(
            MODALITY_MODEL_PATH
        )

        return model

    except Exception as e:

        raise RuntimeError(
            "\n\n"
            "modality classifier weights "
            "could not be loaded.\n\n"
            f"File:\n{MODALITY_MODEL_PATH}\n\n"
            "The architecture generated by "
            "modality_model_builder.py MUST EXACTLY "
            "match the architecture used during "
            "training.\n\n"
            "This is an architecture/weights mismatch, "
            "not a Streamlit threshold problem.\n\n"
            f"Original error:\n{e}"
        ) from e


# ============================================================
# LOAD X-RAY VERIFIER
# ============================================================

@st.cache_resource
def load_xray_model():

    check_model_file(
        XRAY_MODEL_PATH,
        "X-ray verifier weights"
    )

    try:

        model = build_xray_classifier(
            input_shape=(
                XRAY_IMAGE_SIZE[0],
                XRAY_IMAGE_SIZE[1],
                3
            )
        )

        model.load_weights(
            XRAY_MODEL_PATH
        )

        return model

    except Exception as e:

        raise RuntimeError(
            "\n\n"
            "X-ray verifier weights could not be loaded.\n\n"
            f"File:\n{XRAY_MODEL_PATH}\n\n"
            "The architecture generated by "
            "xray_model_builder.py must exactly match "
            "the architecture used during training.\n\n"
            f"Original error:\n{e}"
        ) from e


# ============================================================
# LOAD PNEUMONIA MODEL
# ============================================================

@st.cache_resource
def load_pneumonia_model():

    check_model_file(
        PNEUMONIA_MODEL_PATH,
        "Pneumonia model"
    )

    try:

        # ----------------------------------------------------
        # IMPORTANT
        # ----------------------------------------------------
        # If this is a complete .keras model, it is better
        # to load the complete model directly.
        #
        # Do NOT construct a different architecture and then
        # load incompatible weights into it.
        # ----------------------------------------------------

        model = tf.keras.models.load_model(
            PNEUMONIA_MODEL_PATH,
            compile=False
        )

        return model

    except Exception as e:

        raise RuntimeError(
            "\n\n"
            "Pneumonia model could not be loaded.\n\n"
            f"File:\n{PNEUMONIA_MODEL_PATH}\n\n"
            "Make sure this .keras file contains the "
            "complete trained model and that any custom "
            "layers/functions are available.\n\n"
            f"Original error:\n{e}"
        ) from e


# ============================================================
# LOAD MODELS
# ============================================================

try:

    modality_model = load_modality_model()

except Exception as e:

    st.error(
        "Medical modality classifier loading failed."
    )

    st.exception(e)

    st.stop()


try:

    xray_model = load_xray_model()

except Exception as e:

    st.error(
        "X-ray verifier loading failed."
    )

    st.exception(e)

    st.stop()


try:

    pneumonia_model = load_pneumonia_model()

except Exception as e:

    st.error(
        "Pneumonia model loading failed."
    )

    st.exception(e)

    st.stop()


# ============================================================
# VERIFY MODEL OUTPUTS
# ============================================================

if modality_model.output_shape[-1] != 3:

    st.error(
        "Modality model output mismatch."
    )

    st.write(
        f"Expected: 3 classes"
    )

    st.write(
        f"Received: {modality_model.output_shape}"
    )

    st.stop()


if xray_model.output_shape[-1] != 2:

    st.error(
        "X-ray verifier output mismatch."
    )

    st.write(
        f"Expected: 2 classes"
    )

    st.write(
        f"Received: {xray_model.output_shape}"
    )

    st.stop()


if pneumonia_model.output_shape[-1] != 2:

    st.error(
        "Pneumonia model output mismatch."
    )

    st.write(
        f"Expected: 2 classes"
    )

    st.write(
        f"Received: {pneumonia_model.output_shape}"
    )

    st.stop()


# ============================================================
# HELPER — PROBABILITIES
# ============================================================

def to_probabilities(scores):

    scores = np.asarray(
        scores,
        dtype=np.float64
    )

    if (
        np.all(scores >= 0.0)
        and
        np.all(scores <= 1.0)
        and
        np.isclose(
            np.sum(scores),
            1.0,
            atol=1e-3
        )
    ):

        return scores

    return tf.nn.softmax(
        scores
    ).numpy()


# ============================================================
# COLOR IMAGE CHECK
# ============================================================

def is_grayscale_image(
    image,
    tolerance=COLOR_TOLERANCE
):

    rgb = np.asarray(
        image.convert("RGB"),
        dtype=np.float32
    )

    r = rgb[:, :, 0]

    g = rgb[:, :, 1]

    b = rgb[:, :, 2]

    difference = (

        np.mean(
            np.abs(r - g)
        )

        +

        np.mean(
            np.abs(g - b)
        )

        +

        np.mean(
            np.abs(r - b)
        )

    ) / 3.0

    return (
        difference <= tolerance,
        difference
    )


# ============================================================
# BASIC IMAGE VALIDATION
# ============================================================

def validate_image(image):

    width, height = image.size

    if width < 64 or height < 64:

        return (
            False,
            "Image resolution is too small."
        )


    grayscale, difference = (
        is_grayscale_image(image)
    )

    if not grayscale:

        return (
            False,
            "Color image detected."
        )


    gray = np.asarray(
        image.convert("L"),
        dtype=np.float32
    )


    if np.std(gray) < 8:

        return (
            False,
            "Image appears blank."
        )


    if np.mean(gray < 10) > 0.98:

        return (
            False,
            "Image is almost completely black."
        )


    if np.mean(gray > 245) > 0.98:

        return (
            False,
            "Image is almost completely white."
        )


    return (
        True,
        "Image passed basic validation."
    )


# ============================================================
# PREPROCESS
# ============================================================

def preprocess_image(
    image,
    size
):

    image = image.convert(
        "RGB"
    )

    image = image.resize(
        size,
        Image.Resampling.LANCZOS
    )

    array = np.asarray(
        image,
        dtype=np.float32
    )

    array /= 255.0

    return np.expand_dims(
        array,
        axis=0
    )


# ============================================================
# MODALITY PREDICTION
# ============================================================

def predict_modality(image):

    input_data = preprocess_image(
        image,
        MODALITY_IMAGE_SIZE
    )

    prediction = modality_model.predict(
        input_data,
        verbose=0
    )

    prediction = np.asarray(
        prediction
    )

    if (
        prediction.ndim != 2
        or
        prediction.shape[1] != 3
    ):

        raise ValueError(
            f"Modality classifier must output "
            f"3 classes. Received {prediction.shape}"
        )

    probabilities = to_probabilities(
        prediction[0]
    )

    index = int(
        np.argmax(
            probabilities
        )
    )

    confidence = float(
        probabilities[index]
    )

    label = MODALITY_CLASS_MAP.get(
        index,
        "UNKNOWN"
    )

    return (
        label,
        confidence,
        probabilities
    )


# ============================================================
# X-RAY VERIFICATION
# ============================================================

def verify_xray(image):

    input_data = preprocess_image(
        image,
        XRAY_IMAGE_SIZE
    )

    prediction = xray_model.predict(
        input_data,
        verbose=0
    )

    prediction = np.asarray(
        prediction
    )

    if (
        prediction.ndim != 2
        or
        prediction.shape[1] != 2
    ):

        raise ValueError(
            f"X-ray verifier must output "
            f"2 classes. Received {prediction.shape}"
        )

    probabilities = to_probabilities(
        prediction[0]
    )

    xray_probability = float(
        probabilities[
            XRAY_CLASS_INDEX
        ]
    )

    non_xray_probability = float(
        probabilities[
            NON_XRAY_CLASS_INDEX
        ]
    )

    predicted_index = int(
        np.argmax(
            probabilities
        )
    )

    predicted_label = XRAY_CLASS_MAP.get(
        predicted_index,
        "UNKNOWN"
    )

    is_xray = (

        predicted_label == "X-RAY"

        and

        xray_probability
        >= XRAY_CONFIDENCE_THRESHOLD

    )

    return {
        "is_xray": is_xray,
        "label": predicted_label,
        "confidence": float(
            probabilities[predicted_index]
        ),
        "xray_probability": xray_probability,
        "non_xray_probability": non_xray_probability,
        "probabilities": probabilities
    }


# ============================================================
# PNEUMONIA PREDICTION
# ============================================================

def predict_pneumonia(image):

    input_data = preprocess_image(
        image,
        PNEUMONIA_IMAGE_SIZE
    )

    prediction = pneumonia_model.predict(
        input_data,
        verbose=0
    )

    prediction = np.asarray(
        prediction
    )

    if (
        prediction.ndim != 2
        or
        prediction.shape[1] != 2
    ):

        raise ValueError(
            f"Pneumonia model must output "
            f"2 classes. Received {prediction.shape}"
        )

    probabilities = to_probabilities(
        prediction[0]
    )

    index = int(
        np.argmax(
            probabilities
        )
    )

    label = PNEUMONIA_CLASS_MAP[
        index
    ]

    confidence = float(
        probabilities[index]
    )

    return (
        label,
        confidence,
        probabilities
    )


# ============================================================
# HEADER
# ============================================================

st.title(
    "Pneumonia Detection System"
)

st.write(
    "Medical image modality verification "
    "followed by chest X-ray verification "
    "and pneumonia classification."
)


st.info(
    "Color images, CT scans, MRI images, "
    "and non-X-ray images are rejected."
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header(
        "System Pipeline"
    )

    st.code(
        """
Uploaded Image
      ↓
Grayscale Check
      ↓
Modality Classifier
      ↓
X-RAY / CT / MRI
      ↓
Only X-RAY continues
      ↓
X-ray Verifier
      ↓
X-RAY / NON-XRAY
      ↓
Pneumonia Model
      ↓
Normal / Pneumonia
"""
    )

    st.divider()

    st.write(
        "**Modality classes**"
    )

    st.write(
        "0 — X-RAY"
    )

    st.write(
        "1 — CT"
    )

    st.write(
        "2 — MRI"
    )

    st.divider()

    st.write(
        "**Pneumonia classes**"
    )

    st.write(
        "0 — Normal"
    )

    st.write(
        "1 — Pneumonia"
    )

    st.divider()

    st.caption(
        "Research prototype. "
        "Not intended for clinical diagnosis."
    )


# ============================================================
# FILE UPLOADER
# ============================================================

uploaded_file = st.file_uploader(
    "Upload Medical Image",
    type=[
        "jpg",
        "jpeg",
        "png",
        "bmp",
        "webp"
    ]
)


# ============================================================
# PROCESS IMAGE
# ============================================================

if uploaded_file is not None:

    try:

        image = Image.open(
            io.BytesIO(
                uploaded_file.getvalue()
            )
        )

        image.load()

        image = image.convert(
            "RGB"
        )

    except Exception as e:

        st.error(
            "Unable to read the image."
        )

        st.exception(e)

        st.stop()


    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )


    if st.button(
        "Analyze Image",
        type="primary",
        use_container_width=True
    ):

        # ====================================================
        # STEP 1 — BASIC VALIDATION
        # ====================================================

        st.subheader(
            "Step 1 — Basic Image Validation"
        )

        valid, message = (
            validate_image(
                image
            )
        )

        if not valid:

            st.error(
                f"Rejected: {message}"
            )

            history_entry = (
                f"Rejected - {message} - "
                f"{uploaded_file.name}"
            )

            st.session_state.history.append(
                history_entry
            )

            st.stop()

        st.success(
            "Grayscale image validation passed."
        )


        # ====================================================
        # STEP 2 — MODALITY CLASSIFICATION
        # ====================================================

        st.subheader(
            "Step 2 — Medical Image Modality"
        )

        with st.spinner(
            "Classifying image modality..."
        ):

            try:

                (
                    modality,
                    modality_confidence,
                    modality_probabilities

                ) = predict_modality(
                    image
                )

            except Exception as e:

                st.error(
                    "Modality classification failed."
                )

                st.exception(e)

                st.stop()


        st.write(
            f"**Predicted modality:** {modality}"
        )

        st.write(
            f"**Confidence:** "
            f"{modality_confidence * 100:.2f}%"
        )


        # ----------------------------------------------------
        # MODALITY PROBABILITIES
        # ----------------------------------------------------

        col1, col2, col3 = st.columns(3)

        with col1:

            st.metric(
                "X-RAY",
                f"{modality_probabilities[0] * 100:.2f}%"
            )

        with col2:

            st.metric(
                "CT",
                f"{modality_probabilities[1] * 100:.2f}%"
            )

        with col3:

            st.metric(
                "MRI",
                f"{modality_probabilities[2] * 100:.2f}%"
            )


        # ====================================================
        # REJECT CT
        # ====================================================

        if modality == "CT":

            st.error(
                "CT scan detected."
            )

            st.warning(
                "This system accepts only chest X-ray images."
            )

            st.session_state.history.append(
                f"Rejected - CT - {uploaded_file.name}"
            )

            st.stop()


        # ====================================================
        # REJECT MRI
        # ====================================================

        if modality == "MRI":

            st.error(
                "MRI image detected."
            )

            st.warning(
                "This system accepts only chest X-ray images."
            )

            st.session_state.history.append(
                f"Rejected - MRI - {uploaded_file.name}"
            )

            st.stop()


        # ====================================================
        # UNKNOWN
        # ====================================================

        if modality != "X-RAY":

            st.error(
                "Unsupported image modality."
            )

            st.stop()


        # ====================================================
        # LOW X-RAY CONFIDENCE
        # ====================================================

        if (
            modality_confidence
            < MODALITY_CONFIDENCE_THRESHOLD
        ):

            st.error(
                "X-ray classification confidence is too low."
            )

            st.warning(
                f"Required: "
                f"{MODALITY_CONFIDENCE_THRESHOLD * 100:.0f}%\n\n"
                f"Obtained: "
                f"{modality_confidence * 100:.2f}%"
            )

            st.session_state.history.append(
                f"Rejected - Low X-ray confidence - "
                f"{uploaded_file.name}"
            )

            st.stop()


        st.success(
            "Medical modality confirmed as X-RAY."
        )


        # ====================================================
        # STEP 3 — X-RAY VERIFICATION
        # ====================================================

        st.subheader(
            "Step 3 — Chest X-ray Verification"
        )

        with st.spinner(
            "Verifying chest X-ray..."
        ):

            try:

                xray_result = verify_xray(
                    image
                )

            except Exception as e:

                st.error(
                    "X-ray verification failed."
                )

                st.exception(e)

                st.stop()


        col1, col2 = st.columns(2)

        with col1:

            st.metric(
                "X-ray Probability",
                f"{xray_result['xray_probability'] * 100:.2f}%"
            )

        with col2:

            st.metric(
                "Non-X-ray Probability",
                f"{xray_result['non_xray_probability'] * 100:.2f}%"
            )


        if not xray_result["is_xray"]:

            st.error(
                "This image failed X-ray verification."
            )

            st.warning(
                "Pneumonia classification has been stopped."
            )

            st.session_state.history.append(
                f"Rejected - X-ray verification - "
                f"{uploaded_file.name}"
            )

            st.stop()


        st.success(
            "Chest X-ray verified."
        )


        # ====================================================
        # STEP 4 — PNEUMONIA DETECTION
        # ====================================================

        st.subheader(
            "Step 4 — Pneumonia Detection"
        )

        with st.spinner(
            "Analyzing verified chest X-ray..."
        ):

            try:

                (
                    diagnosis,
                    diagnosis_confidence,
                    pneumonia_probabilities

                ) = predict_pneumonia(
                    image
                )

            except Exception as e:

                st.error(
                    "Pneumonia prediction failed."
                )

                st.exception(e)

                st.stop()


        normal_probability = float(
            pneumonia_probabilities[0]
        )

        pneumonia_probability = float(
            pneumonia_probabilities[1]
        )


        # ====================================================
        # FINAL DIAGNOSIS
        # ====================================================

        if diagnosis == "Pneumonia":

            st.error(
                "Diagnosis: Pneumonia"
            )

        else:

            st.success(
                "Diagnosis: Normal"
            )


        st.subheader(
            "Final Result"
        )


        col1, col2 = st.columns(2)

        with col1:

            st.metric(
                "Normal",
                f"{normal_probability * 100:.2f}%"
            )

            st.progress(
                normal_probability
            )

        with col2:

            st.metric(
                "Pneumonia",
                f"{pneumonia_probability * 100:.2f}%"
            )

            st.progress(
                pneumonia_probability
            )


        st.write(
            f"**Final Diagnosis:** {diagnosis}"
        )

        st.write(
            f"**Diagnosis Confidence:** "
            f"{diagnosis_confidence * 100:.2f}%"
        )


        # ====================================================
        # TECHNICAL INFORMATION
        # ====================================================

        with st.expander(
            "Technical Details"
        ):

            st.write(
                f"Modality: {modality}"
            )

            st.write(
                f"Modality confidence: "
                f"{modality_confidence * 100:.2f}%"
            )

            st.write(
                f"X-ray probability: "
                f"{xray_result['xray_probability'] * 100:.2f}%"
            )

            st.write(
                f"Non-X-ray probability: "
                f"{xray_result['non_xray_probability'] * 100:.2f}%"
            )

            st.write(
                f"Normal probability: "
                f"{normal_probability * 100:.2f}%"
            )

            st.write(
                f"Pneumonia probability: "
                f"{pneumonia_probability * 100:.2f}%"
            )


        # ====================================================
        # HISTORY
        # ====================================================

        st.session_state.history.append(
            f"{diagnosis} - {uploaded_file.name}"
        )


        # ====================================================
        # DISCLAIMER
        # ====================================================

        st.info(
            "This system is a research prototype "
            "and is not intended to provide clinical "
            "diagnosis or replace professional medical "
            "evaluation."
        )
