# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebook#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/rupdasgupta/streamlit-app-py.1fa2ee1a-3bb7-49eb-9674-0a6b0d1a7ce5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260811/auto/storage/goog4_request%26X-Goog-Date%3D20260811T064617Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Da17cb817676cb3660ac3e7c8e8810771b37da434a3e760027f435315a9c670fdcb8fd999c7d212662a37a351dc1510fc4bfe912898e9092a3b73ea2ee88ba5e1a17b1a9dd14bc13dbda2e15810987b567e2456b59f8a49af4b3867d785fc915fa355ed53af594297fbc0c54377e3f4709ef7cb09451d50ddd71f57e8674c66e175948e8ffa80cf5a8049a98afc44a23c43428518e20af00c6f2f0c45520d8717b0f94161efc9ea29f8d8a9cfb158b44389d620627260cd3ff10eef5efdaeae6b3bc8f102cb9cff7c599262d16b6ef9098a90463b4fb99d73bcd3c7d5f30f89fb3e37e90360a56320d85aa4d85b402e3c51ce7a6b8a408caa8e986e8c8a51a421
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
# import kagglehub
# kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

# rupdasgupta_pneumonia_no_preprocessed_path = kagglehub.dataset_download('rupdasgupta/pneumonia-no-preprocessed')

print('Data source import complete.')

# ============================================================
# PNEUMONIA DETECTION MODEL
# Xception-style + Residual + SE Architecture
# Kaggle Training Version
# ============================================================

# ============================================================
# 1. IMPORTS
# ============================================================

import os
import shutil
import random

import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix
)

import tensorflow as tf

from tensorflow.keras import (
    layers,
    Model,
    Input,
    mixed_precision
)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.optimizers import Adam

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ModelCheckpoint,
    ReduceLROnPlateau
)


print("=" * 70)
print("ALL IMPORTS SUCCESSFUL")
print("=" * 70)


# ============================================================
# 2. REPRODUCIBILITY
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print(f"Random seed: {SEED}")


# ============================================================
# 3. GPU SETUP
# ============================================================

gpus = tf.config.list_physical_devices("GPU")

if gpus:

    print(f"\nGPU detected: {len(gpus)}")

    for gpu in gpus:

        try:
            tf.config.experimental.set_memory_growth(
                gpu,
                True
            )
        except RuntimeError as e:
            print(f"GPU memory-growth warning: {e}")

else:

    print("\nWARNING: No GPU detected.")
    print("Training will run on CPU.")


# ============================================================
# 4. MIXED PRECISION
# ============================================================

if gpus:

    mixed_precision.set_global_policy(
        "mixed_float16"
    )

    print(
        "\nMixed precision:",
        mixed_precision.global_policy().name
    )

else:

    mixed_precision.set_global_policy(
        "float32"
    )

    print(
        "\nMixed precision disabled because GPU was not found."
    )


# ============================================================
# 5. SETTINGS
# ============================================================

DATASET_PATH = (
    "/kaggle/input/datasets/rupdasgupta/pneumonia-no-preprocessed/Pnemonia_No_Preprocessed"
)

# IMPORTANT:
# Kaggle input = READ ONLY
# Kaggle working = READ / WRITE

OUTPUT_PATH = (
    "/kaggle/working/pneumonia_split"
)

TRAIN_PATH = os.path.join(
    OUTPUT_PATH,
    "train"
)

VAL_PATH = os.path.join(
    OUTPUT_PATH,
    "val"
)

MODEL_PATH = (
    "/kaggle/working/best_xception_pneumonia_model.keras"
)

TRAINING_PLOT_PATH = (
    "/kaggle/working/training_results.png"
)

CONFUSION_MATRIX_PATH = (
    "/kaggle/working/confusion_matrix.png"
)

IMG_SIZE = (
    224,
    224
)

BATCH_SIZE = 64

EPOCHS = 70

# ============================================================
# CLASS SETTINGS
# ============================================================

CLASSES = [
    "Normal",
    "Pneumonia"
]

IMAGE_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png"
)

NUM_CLASSES = len(CLASSES)


print("\n" + "=" * 70)
print("SETTINGS")
print("=" * 70)

print(f"Dataset:       {DATASET_PATH}")
print(f"Output:        {OUTPUT_PATH}")
print(f"Image size:    {IMG_SIZE}")
print(f"Batch size:    {BATCH_SIZE}")
print(f"Epochs:        {EPOCHS}")
print(f"Classes:       {CLASSES}")
print(f"Num classes:   {NUM_CLASSES}")


# ============================================================
# 6. CHECK DATASET
# ============================================================

print("\n" + "=" * 70)
print("CHECKING DATASET")
print("=" * 70)

if not os.path.isdir(DATASET_PATH):

    raise FileNotFoundError(
        f"\nDataset directory not found:\n"
        f"{DATASET_PATH}"
    )

print(
    f"Dataset found:\n{DATASET_PATH}"
)


# ============================================================
# 7. CHECK CLASS DIRECTORIES
# ============================================================

for cls in CLASSES:

    class_path = os.path.join(
        DATASET_PATH,
        cls
    )

    if not os.path.isdir(class_path):

        raise FileNotFoundError(
            f"\nClass folder not found:\n"
            f"{class_path}\n\n"
            f"Available folders:\n"
            f"{os.listdir(DATASET_PATH)}"
        )

    image_files = [
        f
        for f in os.listdir(class_path)
        if f.lower().endswith(
            IMAGE_EXTENSIONS
        )
    ]

    print(
        f"{cls:<12}: "
        f"{len(image_files)} images"
    )


# ============================================================
# 8. CREATE AUTOMATIC 80/20 SPLIT
# ============================================================

print("\n" + "=" * 70)
print("CREATING AUTOMATIC 80/20 TRAIN / VALIDATION SPLIT")
print("=" * 70)


# Remove old generated split
if os.path.exists(OUTPUT_PATH):

    print(
        f"Removing previous split:\n{OUTPUT_PATH}"
    )

    shutil.rmtree(
        OUTPUT_PATH
    )


# Create directories
for split_path in [
    TRAIN_PATH,
    VAL_PATH
]:

    for cls in CLASSES:

        os.makedirs(
            os.path.join(
                split_path,
                cls
            ),
            exist_ok=True
        )


# ============================================================
# 9. SPLIT EACH CLASS
# ============================================================

total_train = 0
total_val = 0

for cls in CLASSES:

    source_folder = os.path.join(
        DATASET_PATH,
        cls
    )

    all_files = [
        filename
        for filename in os.listdir(
            source_folder
        )
        if filename.lower().endswith(
            IMAGE_EXTENSIONS
        )
    ]

    all_files.sort()

    if len(all_files) == 0:

        raise ValueError(
            f"No images found in:\n"
            f"{source_folder}"
        )

    # --------------------------------------------------------
    # 80/20 split
    # --------------------------------------------------------

    train_files, val_files = train_test_split(
        all_files,
        test_size=0.20,
        random_state=SEED,
        shuffle=True
    )

    # --------------------------------------------------------
    # Copy training files
    # --------------------------------------------------------

    for filename in train_files:

        source_file = os.path.join(
            source_folder,
            filename
        )

        destination_file = os.path.join(
            TRAIN_PATH,
            cls,
            filename
        )

        shutil.copy2(
            source_file,
            destination_file
        )

    # --------------------------------------------------------
    # Copy validation files
    # --------------------------------------------------------

    for filename in val_files:

        source_file = os.path.join(
            source_folder,
            filename
        )

        destination_file = os.path.join(
            VAL_PATH,
            cls,
            filename
        )

        shutil.copy2(
            source_file,
            destination_file
        )

    total_train += len(
        train_files
    )

    total_val += len(
        val_files
    )

    print(
        f"{cls:<12} | "
        f"Train: {len(train_files):>5} | "
        f"Validation: {len(val_files):>5} | "
        f"Total: {len(all_files):>5}"
    )


# ============================================================
# 10. VERIFY SPLIT
# ============================================================

print("\n" + "=" * 70)
print("SPLIT COMPLETED")
print("=" * 70)

print(
    f"Total training images:   {total_train}"
)

print(
    f"Total validation images: {total_val}"
)

print(
    f"Total images:             "
    f"{total_train + total_val}"
)

print(
    f"\nTraining path:\n{TRAIN_PATH}"
)

print(
    f"\nValidation path:\n{VAL_PATH}"
)


# ============================================================
# 11. SE ATTENTION BLOCK
# ============================================================

def se_block(
    x,
    reduction=16
):

    channels = x.shape[-1]

    if channels is None:

        raise ValueError(
            "Number of channels must be known."
        )

    reduced_channels = max(
        channels // reduction,
        4
    )

    se = layers.GlobalAveragePooling2D()(
        x
    )

    se = layers.Dense(
        reduced_channels,
        activation="gelu"
    )(se)

    se = layers.Dense(
        channels,
        activation="sigmoid"
    )(se)

    se = layers.Reshape(
        (1, 1, channels)
    )(se)

    return layers.Multiply()(
        [x, se]
    )


# ============================================================
# 12. CONVOLUTION BLOCK
# ============================================================

def conv_block(
    x,
    filters,
    kernel_size=3,
    strides=1
):

    x = layers.Conv2D(
        filters,
        kernel_size,
        strides=strides,
        padding="same",
        use_bias=False
    )(x)

    x = layers.BatchNormalization()(
        x
    )

    x = layers.Activation(
        "gelu"
    )(x)

    return x


# ============================================================
# 13. XCEPTION BLOCK
# ============================================================

def xception_block(
    x,
    filters
):

    shortcut = x

    x = layers.SeparableConv2D(
        filters,
        3,
        padding="same",
        use_bias=False
    )(x)

    x = layers.BatchNormalization()(
        x
    )

    x = layers.Activation(
        "gelu"
    )(x)

    x = layers.SeparableConv2D(
        filters,
        3,
        padding="same",
        use_bias=False
    )(x)

    x = layers.BatchNormalization()(
        x
    )

    if shortcut.shape[-1] != filters:

        shortcut = layers.Conv2D(
            filters,
            1,
            padding="same",
            use_bias=False
        )(shortcut)

        shortcut = layers.BatchNormalization()(
            shortcut
        )

    x = layers.Add()(
        [x, shortcut]
    )

    x = layers.Activation(
        "gelu"
    )(x)

    x = se_block(
        x
    )

    return x


# ============================================================
# 14. RESIDUAL BLOCK
# ============================================================

def residual_block(
    x,
    filters
):

    shortcut = x

    x = conv_block(
        x,
        filters,
        3
    )

    x = conv_block(
        x,
        filters,
        3
    )

    if shortcut.shape[-1] != filters:

        shortcut = layers.Conv2D(
            filters,
            1,
            padding="same",
            use_bias=False
        )(shortcut)

        shortcut = layers.BatchNormalization()(
            shortcut
        )

    x = layers.Add()(
        [x, shortcut]
    )

    x = layers.Activation(
        "gelu"
    )(x)

    return x


# ============================================================
# 15. BUILD MODEL
# ============================================================

def build_model(
    input_shape=(224, 224, 3),
    num_classes=2
):

    inputs = Input(
        shape=input_shape
    )

    # --------------------------------------------------------
    # Stem
    # --------------------------------------------------------

    x = conv_block(
        inputs,
        16,
        3
    )

    x = layers.MaxPooling2D(
        2
    )(x)

    # --------------------------------------------------------
    # Xception block
    # --------------------------------------------------------

    x = xception_block(
        x,
        32
    )

    x = layers.MaxPooling2D(
        2
    )(x)

    # --------------------------------------------------------
    # Residual block
    # --------------------------------------------------------

    x = residual_block(
        x,
        64
    )

    x = layers.MaxPooling2D(
        2
    )(x)

    # --------------------------------------------------------
    # Residual block
    # --------------------------------------------------------

    x = residual_block(
        x,
        128
    )

    x = layers.MaxPooling2D(
        2
    )(x)

    # --------------------------------------------------------
    # Residual block
    # --------------------------------------------------------

    x = residual_block(
        x,
        128
    )

    # --------------------------------------------------------
    # Classification head
    # --------------------------------------------------------

    x = layers.GlobalAveragePooling2D()(
        x
    )

    x = layers.BatchNormalization()(
        x
    )

    x = layers.Dense(
        256,
        activation="gelu"
    )(x)

    x = layers.Dropout(
        0.3
    )(x)

    # --------------------------------------------------------
    # Output
    # --------------------------------------------------------

    x = layers.Dense(
        num_classes
    )(x)

    # Mixed precision:
    # final output must be float32
    outputs = layers.Activation(
        "softmax",
        dtype="float32"
    )(x)

    return Model(
        inputs,
        outputs
    )


# ============================================================
# 16. DATA GENERATORS
# ============================================================

print("\n" + "=" * 70)
print("CREATING DATA GENERATORS")
print("=" * 70)


train_datagen = ImageDataGenerator(
    rescale=1.0 / 255.0,

    rotation_range=15,

    width_shift_range=0.10,

    height_shift_range=0.10,

    horizontal_flip=True,

    zoom_range=0.10
)


val_datagen = ImageDataGenerator(
    rescale=1.0 / 255.0
)


train_generator = train_datagen.flow_from_directory(
    TRAIN_PATH,

    target_size=IMG_SIZE,

    batch_size=BATCH_SIZE,

    class_mode="sparse",

    shuffle=True,

    seed=SEED
)


val_generator = val_datagen.flow_from_directory(
    VAL_PATH,

    target_size=IMG_SIZE,

    batch_size=BATCH_SIZE,

    class_mode="sparse",

    shuffle=False
)


print(
    "\nClass indices:"
)

print(
    train_generator.class_indices
)


# ============================================================
# 17. VERIFY CLASS MAPPING
# ============================================================

expected_mapping = {
    "Normal": 0,
    "Pneumonia": 1
}

if train_generator.class_indices != expected_mapping:

    raise ValueError(
        "\nUnexpected class mapping!\n"
        f"Expected: {expected_mapping}\n"
        f"Found:    {train_generator.class_indices}"
    )

print(
    "\n✓ Correct class mapping:"
)

print(
    "  0 = Normal"
)

print(
    "  1 = Pneumonia"
)


# ============================================================
# 18. CALCULATE CLASS WEIGHTS
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING CLASS WEIGHTS")
print("=" * 70)


class_counts = {}

for cls in CLASSES:

    class_folder = os.path.join(
        TRAIN_PATH,
        cls
    )

    count = len(
        [
            f
            for f in os.listdir(
                class_folder
            )
            if f.lower().endswith(
                IMAGE_EXTENSIONS
            )
        ]
    )

    class_counts[
        train_generator.class_indices[cls]
    ] = count

    print(
        f"{cls:<12}: {count} images"
    )


total_samples = sum(
    class_counts.values()
)


class_weight = {
    class_id:
        total_samples /
        (
            NUM_CLASSES *
            count
        )

    for class_id, count
    in class_counts.items()
}


print(
    "\nClass weights:"
)

print(
    class_weight
)


# ============================================================
# 19. BUILD MODEL
# ============================================================

print("\n" + "=" * 70)
print("BUILDING MODEL")
print("=" * 70)


model = build_model(
    input_shape=(
        IMG_SIZE[0],
        IMG_SIZE[1],
        3
    ),

    num_classes=NUM_CLASSES
)


model.summary()


# ============================================================
# 20. COMPILE MODEL
# ============================================================

model.compile(

    optimizer=Adam(
        learning_rate=1e-4
    ),

    loss="sparse_categorical_crossentropy",

    metrics=[
        "accuracy"
    ]
)


print(
    "\n✓ Model compiled successfully."
)


# ============================================================
# 21. CALLBACKS
# ============================================================

early_stop = EarlyStopping(

    monitor="val_loss",

    patience=5,

    restore_best_weights=True,

    verbose=1
)


checkpoint = ModelCheckpoint(

    MODEL_PATH,

    monitor="val_accuracy",

    save_best_only=True,

    mode="max",

    verbose=1
)


reduce_lr = ReduceLROnPlateau(

    monitor="val_loss",

    factor=0.5,

    patience=3,

    min_lr=1e-6,

    verbose=1
)


# ============================================================
# 22. TRAIN MODEL
# ============================================================

print("\n" + "=" * 70)
print("STARTING TRAINING")
print("=" * 70)


history = model.fit(

    train_generator,

    validation_data=val_generator,

    epochs=EPOCHS,

    class_weight=class_weight,

    callbacks=[
        early_stop,
        checkpoint,
        reduce_lr
    ],

    verbose=1
)


print("\n" + "=" * 70)
print("TRAINING COMPLETED")
print("=" * 70)

print(
    f"Best model saved at:\n{MODEL_PATH}"
)


# ============================================================
# 23. LOAD BEST MODEL
# ============================================================

print(
    "\nLoading best saved model..."
)

best_model = tf.keras.models.load_model(
    MODEL_PATH
)

print(
    "✓ Best model loaded."
)


# ============================================================
# 24. TRAINING HISTORY
# ============================================================

plt.figure(
    figsize=(12, 5)
)

plt.subplot(
    1,
    2,
    1
)

plt.plot(
    history.history["accuracy"],
    label="Train Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.title(
    "Training and Validation Accuracy"
)

plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Accuracy"
)

plt.legend()


plt.subplot(
    1,
    2,
    2
)

plt.plot(
    history.history["loss"],
    label="Train Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.title(
    "Training and Validation Loss"
)

plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Loss"
)

plt.legend()


plt.tight_layout()

plt.savefig(
    TRAINING_PLOT_PATH,
    dpi=300,
    bbox_inches="tight"
)

plt.show()


print(
    f"\nTraining graph saved:\n"
    f"{TRAINING_PLOT_PATH}"
)


# ============================================================
# 25. VALIDATION PREDICTIONS
# ============================================================

print("\n" + "=" * 70)
print("VALIDATION EVALUATION")
print("=" * 70)


val_generator.reset()


y_pred_probs = best_model.predict(
    val_generator,
    verbose=1
)


y_pred = np.argmax(
    y_pred_probs,
    axis=1
)


y_true = val_generator.classes


# ============================================================
# 26. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("CLASSIFICATION REPORT")
print("=" * 70)


print(
    classification_report(
        y_true,
        y_pred,
        target_names=CLASSES,
        digits=4
    )
)


# ============================================================
# 27. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_true,
    y_pred
)


print("\nConfusion Matrix:")
print(cm)


plt.figure(
    figsize=(7, 6)
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=CLASSES,
    yticklabels=CLASSES
)

plt.title(
    "Confusion Matrix"
)

plt.ylabel(
    "True Label"
)

plt.xlabel(
    "Predicted Label"
)

plt.tight_layout()

plt.savefig(
    CONFUSION_MATRIX_PATH,
    dpi=300,
    bbox_inches="tight"
)

plt.show()


print(
    f"\nConfusion matrix saved:\n"
    f"{CONFUSION_MATRIX_PATH}"
)


# ============================================================
# 28. FINAL VALIDATION ACCURACY
# ============================================================

loss, accuracy = best_model.evaluate(
    val_generator,
    verbose=0
)


print("\n" + "=" * 70)
print("FINAL VALIDATION RESULT")
print("=" * 70)

print(
    f"Validation Loss:     {loss:.4f}"
)

print(
    f"Validation Accuracy: {accuracy * 100:.2f}%"
)


# ============================================================
# 29. MODEL INFORMATION
# ============================================================

total_params = best_model.count_params()


print("\n" + "=" * 70)
print("MODEL INFORMATION")
print("=" * 70)

print(
    f"Total parameters: {total_params:,}"
)

print(
    f"Model file:       {MODEL_PATH}"
)

print(
    f"Model size:       "
    f"{os.path.getsize(MODEL_PATH) / (1024 ** 2):.2f} MB"
)


# ============================================================
# 30. FINAL OUTPUT FILES
# ============================================================

print("\n" + "=" * 70)
print("KAGGLE OUTPUT FILES")
print("=" * 70)

print(
    f"Model:\n{MODEL_PATH}"
)

print(
    f"\nTraining graph:\n{TRAINING_PLOT_PATH}"
)

print(
    f"\nConfusion matrix:\n{CONFUSION_MATRIX_PATH}"
)

print("\n✓ COMPLETE.")
